### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Sanmejie** [Lucifer1993/AngelSword#11]
环境：
win10
Python 3.9.0

python AngelSword.py
`AngelSword.py:248: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if line.find(keywords) is not -1:
E:\tongzhuopy\play\AngelSword\AngelSword.py:277: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if keyword.__str__().find(sys.argv[2].strip()) is not -1:
E:\tongzhuopy\play\AngelSword\AngelSword.py:314: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if keyword.__str__().find(sys.argv[2].strip()) is not -1:
E:\tongzhuopy\play\AngelSword\AngelSword.py:348: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if keyword.__str__().find(pocfuck) is not -1:
E:\tongzhuopy\play\AngelSword\AngelSword.py:419: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if line.find("BaseVerify") is not -1:
a bytes-like object is required, not 'str'`

**Comment by Sanmejie** [comment]
刚看到停止维护了， 不支持windows，打扰了。

**Comment by Lucifer1993** [comment]
python版本3.5/3.6/3.7都支持,3.8部分小版本支持

**Comment by Sanmejie** [comment]
&nbsp;谢答~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lucifer1993"<notifications@github.com&gt;; 
发送时间: 2021年1月29日(星期五) 晚上6:03
收件人: "Lucifer1993/AngelSword"<AngelSword@noreply.github.com&gt;; 
抄送: "三姩"<sssssssssssi123456@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Lucifer1993/AngelSword] 运行报错 (#11)





 
python版本3.5/3.6/3.7都支持,3.8部分小版本支持
